# Generated by Django 3.1.4 on 2021-02-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201225_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientist',
            name='Bigregion',
            field=models.CharField(choices=[('cfo', 'Центральный Федеральный Округ'), ('szfo', 'Северо-Западный Федеральный Округ'), ('yfo', 'Южный Федеральный Округ'), ('skfo', 'Северо-Кавказский Федеральный Округ'), ('pfo', 'Приволжский Федеральный Округ'), ('urfo', 'Уральский Федеральный Округ'), ('sfo', 'Сибирский Федеральный Округ'), ('dfo', 'Дальневосточный Федеральный Округ')], default='cfo', max_length=60, verbose_name='Федеральный округ'),
        ),
    ]
